version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=communicator_bridge
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DB_NAME=communicator_bridge
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=postgres
      - DB_PORT=5432

volumes:
  postgres_data: