# Generated by Django 5.2.5 on 2025-08-20 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Canais", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(help_text="O conteúdo textual da mensagem."),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que a mensagem foi criada.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIADA", "Enviada"),
                            ("ENTREGUE", "Entregue"),
                            ("LIDA", "Lida"),
                            ("FALHOU", "Falhou"),
                        ],
                        default="ENVIADA",
                        help_text="O status atual da mensagem.",
                        max_length=10,
                    ),
                ),
                (
                    "id_externo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da mensagem no sistema externo (ex: Telegram, WhatsApp).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "canal",
                    models.ForeignKey(
                        help_text="Canal pelo qual a mensagem foi enviada.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensagens",
                        to="Canais.canal",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        help_text="Usuário que recebeu a mensagem (Atendente ou Contato).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_recebidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "remetente",
                    models.ForeignKey(
                        help_text="Usuário que enviou a mensagem (Atendente ou Contato).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["-data_envio"],
            },
        ),
    ]
