# Generated by Django 5.2.5 on 2025-08-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("ADMINISTRADOR", "Administrador"),
                    ("ATENDENTE", "Atendente"),
                    ("CONTATO", "Contato"),
                ],
                default="CONTATO",
                max_length=20,
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
