# Generated by Django 5.2.5 on 2025-08-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_tipo_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Número de telefone do usuário (se aplicável).",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
