# Generated by Django 5.2.5 on 2025-08-20 23:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do canal de comunicação (ex: 'Telegram', 'Facebook Messenger')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TELEGRAM", "Telegram"),
                            ("FACEBOOK", "Facebook Messenger"),
                            ("SLACK", "Slack"),
                            ("MOCK", "Canal Mock"),
                        ],
                        help_text="O tipo de plataforma de comunicação",
                        max_length=50,
                    ),
                ),
                (
                    "configuracao",
                    models.JSONField(
                        help_text="Configurações específicas do canal (ex: token do bot, segredo do webhook)"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Canais",
            },
        ),
    ]
