# Generated by Django 5.2.5 on 2025-08-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Canais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="canal",
            name="ativo",
            field=models.BooleanField(
                default=True, help_text="Indica se o canal está ativo"
            ),
        ),
    ]
